SCREEN_WIDTH = 256
SCREEN_HEIGHT = 149
TITLE = "Slime Jump"

GROUND_Y = 140
GROUND_HEIGHT = 20
PLAYER_START_X = 100
PLAYER_START_Y = 125
PLAYER_SIZE = 16
PLAYER_SPEED = 2

GRAVITY = 0.9
JUMP_FORCE = -10
MAX_JUMPS = 2

# Цвета (если используются)
COLOR_PLAYER = 11
COLOR_GROUND = 10

# Текст меню
MENU_TITLE = "SLIME JUMP"
MENU_START_TEXT = "PRESS ENTER TO START"
MENU_CONTROLS_TEXT = "USE THE ARROWS TO MOVE AND JUMP"

# Координаты текста
TEXT_TITLE_X = 110
TEXT_TITLE_Y = 60
TEXT_START_X = 90
TEXT_START_Y = 80
TEXT_CONTROLS_X = 70
TEXT_CONTROLS_Y = 110
